apiVersion: apps/v1
kind: Deployment
metadata:
  name: dngty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dngty
  template:
    metadata:
      labels:
        app: dngty
    spec:
      containers:
      - image: okteto.dev/dngty:latest
        name: dngty
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "77477fa2-e679-4711-944f-2df21196f447"
        - name: Vless_Path
          value: "/vldg55"
        - name: Vmess_UUID
          value: "77477fa2-e679-4711-944f-2df21196f447"
        - name: Vmess_Path
          value: "/vm6dg6"
        - name: Share_Path
          value: "/v2link"
